let token=localStorage.getItem("fh_token"), me=null;
async function api(url,opt={}){opt.headers={...(opt.headers||{}),...(token?{Authorization:"Bearer "+token}:{})};if(opt.body&&typeof opt.body!=="string"){opt.headers["Content-Type"]="application/json";opt.body=JSON.stringify(opt.body)}const r=await fetch(url,opt);const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Terjadi kesalahan");return d}
function closeModal(){document.getElementById("modal").classList.remove("show")}
function showAuth(type){document.getElementById("modal").classList.add("show");document.getElementById("modalBody").innerHTML=type==="login"?`<h2>Masuk</h2><form class="form" onsubmit="login(event)"><input id="email" type="email" placeholder="Email" required><input id="pass" type="password" placeholder="Password" required><button class="btn">Masuk</button><small>Belum punya akun? <a href="#" onclick="showAuth('register')">Daftar gratis</a></small></form>`:`<h2>Daftar Gratis</h2><form class="form" onsubmit="register(event)"><input id="name" placeholder="Nama lengkap" required><input id="email" type="email" placeholder="Email" required><select id="role"><option value="freelancer">Freelancer</option><option value="client">Client</option></select><input id="pass" type="password" minlength="6" placeholder="Password minimal 6 karakter" required><button class="btn">Buat Akun</button></form>`}
async function login(e){e.preventDefault();try{let d=await api("/api/auth/login",{method:"POST",body:{email:email.value,password:pass.value}});localStorage.setItem("fh_token",d.token);token=d.token;location.href="/dashboard.html"}catch(x){alert(x.message)}}
async function register(e){e.preventDefault();try{let d=await api("/api/auth/register",{method:"POST",body:{name:name.value,email:email.value,password:pass.value,role:role.value}});localStorage.setItem("fh_token",d.token);token=d.token;location.href="/dashboard.html"}catch(x){alert(x.message)}}
async function loadMe(){try{me=(await api("/api/me")).user;document.getElementById("auth").innerHTML=`<a class="btn light" href="/dashboard.html">${me.name}</a><button class="btn" onclick="logout()">Keluar</button>`}catch{}}
function logout(){localStorage.removeItem("fh_token");location.reload()}
async function loadJobs(){let params=new URLSearchParams({q:document.getElementById("q")?.value||"",category:document.getElementById("cat")?.value||""});try{let d=await api("/api/jobs?"+params);document.getElementById("jobsList").innerHTML=d.jobs.length?d.jobs.map(j=>`<article class="card"><small>${j.category}</small><h3>${esc(j.title)}</h3><p class="muted">${esc(j.description)}</p><div class="tags">${(j.skills||"").split(",").filter(Boolean).map(x=>`<span>${esc(x.trim())}</span>`).join("")}</div><div class="price">${esc(j.budget)}</div><small>${esc(j.client_name||"Client")} · ${j.created_at.slice(0,10)}</small><br><button class="btn" style="margin-top:13px" onclick="apply(${j.id})">Ajukan Proposal</button></article>`).join(""):`<div class="card">Belum ada proyek yang cocok.</div>`;document.getElementById("featured").innerHTML=d.jobs.slice(0,3).map(j=>`<div class="mini"><b>${esc(j.title)}</b><span>${esc(j.budget)} · ${esc(j.category)}</span></div>`).join("")}catch(e){console.error(e)}}
function esc(s){return String(s||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function requireLogin(action){if(!token)return showAuth("login");if(action==="post")showPost()}
function showPost(){document.getElementById("modal").classList.add("show");document.getElementById("modalBody").innerHTML=`<h2>Pasang Proyek</h2><form class="form" onsubmit="postJob(event)"><input id="title" placeholder="Judul proyek" required><select id="category"><option>Desain</option><option>Programming</option><option>Writing</option><option>Marketing</option><option>Video</option></select><input id="budget" placeholder="Budget, contoh Rp1.000.000" required><input id="skills" placeholder="Skill, pisahkan koma"><textarea id="description" placeholder="Deskripsi pekerjaan" required></textarea><button class="btn">Publikasikan</button></form>`}
async function postJob(e){e.preventDefault();try{await api("/api/jobs",{method:"POST",body:{title:title.value,category:category.value,budget:budget.value,skills:skills.value,description:description.value}});closeModal();loadJobs();alert("Proyek berhasil dipublikasikan.")}catch(x){alert(x.message)}}
async function apply(id){if(!token)return showAuth("login");document.getElementById("modal").classList.add("show");document.getElementById("modalBody").innerHTML=`<h2>Ajukan Proposal</h2><form class="form" onsubmit="sendBid(event,${id})"><input id="amount" placeholder="Nominal penawaran" required><textarea id="proposal" placeholder="Tulis proposal dan pengalamanmu" required></textarea><button class="btn">Kirim Proposal</button></form>`}
async function sendBid(e,id){e.preventDefault();try{await api("/api/bids",{method:"POST",body:{job_id:id,amount:amount.value,proposal:proposal.value}});closeModal();alert("Proposal terkirim.")}catch(x){alert(x.message)}}
loadMe();loadJobs();